### ISSUE TITLE
[Docs]  Update README

### ISSUE THREAD

**Issue by ml019** [hamlet-io/docker-hamlet#38]
## Documentation Topic
README - image naming

## Description
Update the README to reflect the latest approach to naming of container images

## Audience
Anyone wanting to use the hamlet docker images

## Checklist
The following locations should be reviewed for documentation
- https://docs.hamlet.io/ (everyone)
- https://help.hamlet.io (everyone)
- Applicable repository README.md (developers of Hamlet Deploy only)
- Architectural Decision Log (developers of Hamlet Deploy only)

**Comment by RossMurr4y** [comment]
@ml019 is the checklist you've mentioned requiring review of content that is specific to docker images? Because if you are looking for a broader review then I think we need to track those things individually.

**Comment by ml019** [comment]
@RossMurr4y  The actual README in this repo needs updating becuase the format of docker images it describes is out of date I think.

**Comment by roleyfoley** [comment]
@ml019 I've reviewed the README and compared to the images currently in dockerhub this is correct.

**Comment by ml019** [comment]
@roleyfoley in the section on pipeline agents, I thing the `-<base>` is optional so maybe put in braces? If I understand, it is used where the base image also has an extension so maybe add a note to say "optional base extension aligns to any value used in naming the base image used"?
